[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit MPU6050 @ ^2.2.4
	adafruit/Adafruit Unified Sensor @ ^1.1.9
	oxullo/MAX30100lib @ ^1.2.1
	sinricpro/SinricPro @ ^3.2.0

build_flags = -Wall -O2 -D NDEBUG
build_type = release

[env:debug]
build_flags = -D DEBUG

; Build flags
; DEBUG enables debug output
; LANG_BR enables portuguese alerts, by default it's english
; DISABLE_OXM disables the oximeter in case needed. Useful for testing the mpu6050 when in a breadboard.
; Example:
; build_flags = -D DEBUG -D LANG_BR -D DISABLE_OXM
